---
appendix: "Stage2_app002.Rmd"
---

```{r setup_b, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
```

# Data Collection Logs

The log website was initiated since the data collection began. The public logs were updated when a laboratory updated their data for the sequential analysis. The link to access the public site is: https://scgeeker.github.io/PSA002_log_site/index.html

If you want to check the sequential analysis result of a laboratory, at first you have to identify the ID and language of this laboratory from "Overview" page. Next you will navigate to the language page under the banner "Tracking Logs". For example, you want to see the result of "GBR_005". Navigate "Tracking Logs -> English". Search the figure by ID "GBR_005".

The source files of the public logs are available in the github repository:
https://github.com/SCgeeker/PSA002_log_site

All the raw data and log files are compressed in the project OSF repository: https://osf.io/e428p/

The R code to conduct the Bayesian sequential analysis is available at "data_seq_analysis.R". This file can be found at: https://github.com/SCgeeker/PSA002_log_site 

**Note 1** USA_067, BRA_004 and POL_004 were unavailable because the teams withdrew.

**Note 2** Some mistakes happened between the collaborators' communications and required advanced data wrangling. For example, some AUS_091 participants were assigned to NZL_005. The Rmd file in NZL_005 folder were used to identify the AUS_091 participants' data then move them to AUS_091 folder.

## Datasets

Complete data can be found online with this manuscript or on each collaborators OSF page. Please see the `Lab_Info.csv` on https://osf.io/e428p/. 

## Flunecy test for the online study

At the beginning of the online study, participants will hear the verbal instruction narrated by a native speaker. The original English transcript is as below:

"In this session you will complete two tasks. The first task is called the sentence picture verification task. In this task, you will read a sentence. You will then see a picture. Your job is to verify whether the picture represents an object that was described in the sentence or not. The second task is the picture verification task. In this task you will see two pictures on the screen at the same time and determine whether they are the same or different. Once you have completed both tasks, you will receive a completion code that you can use to verify your participation in the study. "

The fluency test are three multiple choice questions. The question text and the correct answers are as below:

- How many tasks will you run in this session?	
A: 1
*B: 2
C: 3	

- When will you get the completion code?	
A: Before the second task
B: After the first task
*C: After the second task	

- What will you do in the sentence-picture verification task?	
A: Confirm two pictures for their objects  
*B: Read a sentence and verify a picture
C: Judge sentences for their accuracy

## Distributions of scripts

The instructions and experimental scripts are available at the public OSF folder (https://osf.io/e428p/ "Materials/js" folder in Files). To upload to a jatos server, a script had to be converted to the compatible package. Researchers could do this conversion by "OSWEB" package in OpenSesame. We rent an remote server for the distributions during the data collection period. Any researcher would distribute the scripts on a free jatos server such as MindProbe (https://www.mindprobe.eu/).


