---
appendix: Stage2_app004.Rmd
---

# Model Estimates for Mental Simulation 

```{r setup_d, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	include = TRUE
)
```

All model estimates are given below for the planned mixed linear model to estimate the matching effect for object orientation in the sentence picture verification task.

*Note*. Fixed indicates fixed parameters in multilevel models, while "ran_pars" indicates the random intercepts included in the model. 

\newpage

```{r intercept, results='asis'}
temp <- tidy(intercept.model)
temp[ , 5] <- apply(temp[ , 5], 2, apa_p)

apa_table(temp, 
          format = "latex", 
          col.names = c("Term", "Estimate ($b$)", "$SE$", "$t$", "$p$"), 
          caption = "Intercept Only Object Orientation Results") 
```

```{r subject, results='asis'}
temp <- tidy(subject.model)
temp[ , 8] <- apply(temp[ , 8], 2, apa_p)

apa_table(temp, 
          format = "latex", 
          col.names = c("Effect", "Group", "Term", "Estimate ($b$)", "$SE$",  "$t$", "$df$", "$p$"), 
          caption = "Subject-Random Intercept Object Orientation Results") 
```

```{r item, results='asis'}
temp <- tidy(item.model)
temp[ , 8] <- apply(temp[ , 8], 2, apa_p)

apa_table(temp, 
          format = "latex", 
          col.names = c("Effect", "Group", "Term", "Estimate ($b$)", "$SE$",  "$t$", "$df$", "$p$"), 
          caption = "Subject and Item-Random Intercept Object Orientation Results") 
```

```{r lab, results='asis'}
temp <- tidy(lab.model)
temp[ , 8] <- apply(temp[ , 8], 2, apa_p)

apa_table(temp, 
          format = "latex", 
          col.names = c("Effect", "Group", "Term", "Estimate ($b$)", "$SE$",  "$t$", "$df$", "$p$"), 
          caption = "Subject, Item, and Lab-Random Intercept Object Orientation Results") 
```

```{r lang, results='asis'}
temp <- tidy(language.model)
temp[ , 8] <- apply(temp[ , 8], 2, apa_p)

apa_table(temp, 
          format = "latex", 
          col.names = c("Effect", "Group", "Term", "Estimate ($b$)", "$SE$",  "$t$", "$df$", "$p$"), 
          caption = "Subject, Item, Lab, and Language-Random Intercept Object Orientation Results") 
```

```{r fixed, results='asis'}
temp <- tidy(fixed.model)
temp[ , 8] <- apply(temp[ , 8], 2, apa_p)

apa_table(temp, 
          format = "latex", 
          col.names = c("Effect", "Group", "Term", "Estimate ($b$)", "$SE$",  "$t$", "$df$", "$p$"), 
          caption = "Fixed Effects Object Orientation Results") 
```

```{r german-random, results='asis'}
temp <- tidy(german.lab.model)
temp[ , 8] <- apply(temp[ , 8], 2, apa_p)

apa_table(temp, 
          format = "latex", 
          col.names = c("Effect", "Group", "Term", "Estimate ($b$)", "$SE$",  "$t$", "$df$", "$p$"), 
          caption = "Random Effects German Object Orientation Results") 
```

```{r german-fixed, results='asis'}
temp <- tidy(german.fixed.three.model)
temp[ , 8] <- apply(temp[ , 8], 2, apa_p)

apa_table(temp, 
          format = "latex", 
          col.names = c("Effect", "Group", "Term", "Estimate ($b$)", "$SE$",  "$t$", "$df$", "$p$"), 
          caption = "Fixed Effects German Object Orientation Results") 
```
